### ISSUE TITLE
SPM not working on 'package' branch

### ISSUE THREAD

**Issue by rebeloper** [eyeson-team/ios-sdk#1]
Hi,

I added the 'package' branch, but it failed to compile on the Simulator and on an iPhone. See attached Screenshots
![CleanShot 2022-08-08 at 18 46 42@2x](https://user-images.githubusercontent.com/2488011/183459453-4fb5e320-c3d5-43d8-bb54-7e8a1826174c.png)
![CleanShot 2022-08-08 at 18 47 05@2x](https://user-images.githubusercontent.com/2488011/183459478-43c4b6bc-ecaf-4193-8b26-8a18af0a3b43.png)
![CleanShot 2022-08-08 at 18 47 14@2x](https://user-images.githubusercontent.com/2488011/183459483-31b5d76d-2308-4f03-be43-4799937c011c.png)

Looking forward to your reply,
Alex

**Comment by mmaier** [comment]
Hi Alex,
we are currently working on this issue, which demands a deeper investigation from our side. We will keep you updated.
Best regards, Michael

**Comment by mmaier** [comment]
Hi Alex,

builds do not succeed for iOS Simulator because of WebRTC library architecture issues. Please use a real device to test the SDK. We did some major updates in our Swift package which need to be updated. To do so, please follow these steps:

1) Clean existing project:
- Remove the Eyeson package from your current project
- Choose Product > Clean Build Folder

2) Re-add package:
- Choose File > Add Packages 
- From repository: https://github.com/eyeson-team/ios-sdk
- Select Dependency Rule "Branch" with value "package"
 
3) Reset package cache before you make a new build:
- Choose File > Packages > Reset Package Caches
- After completion, right mouse click on the Eyeson package and choose "Update Package"

You should now have the updated package in your project.
If you have any questions, feel free to reach out to me.

Best regards,
Michael
